import type { Config } from './config.ts';

export function buildMediamtxYaml(env: Config) {
	return `# generated by packages/stream supervisor — do not edit by hand
# mediamtx: ${env.MEDIAMTX_BIN}
logLevel: info
logDestinations: [stdout]
logStructured: false

rtsp: no
rtmp: no
srt: no
webrtc: no

api: yes
apiAddress: :${env.MEDIAMTX_API_PORT}

hls: yes
hlsAddress: :${env.MEDIAMTX_HLS_PORT}
hlsAlwaysRemux: yes
hlsVariant: mpegts
hlsSegmentCount: ${env.HLS_SEGMENT_COUNT}
hlsSegmentDuration: 2s
hlsDirectory: ${env.HLS_DIR}
hlsAllowOrigins: ['*']

paths:
  trask:
    source: ${env.RTSP_URL}
    sourceOnDemand: no
    rtspTransport: tcp
`;
}
